import type { Project } from "@/lib/types/project";
import type { KnowledgeItem } from "@/lib/types/knowledge";
import type { Conflict } from "@/lib/types/conflict";
import type { TimelineEvent } from "@/lib/types/event";
import { formatDate } from "@/lib/utils/helpers";

export function buildKnowledgeMarkdown(
  item: KnowledgeItem,
  slug: string
): string {
  const lines: string[] = [];
  lines.push(`# ${item.id} — ${item.name}`);
  lines.push("");
  lines.push(
    `**Confidence:** ${item.confidence}% · **Status:** ${item.status} · **Category:** ${item.category} · **Updated:** ${formatDate(item.updatedAt)}`
  );
  lines.push("");
  lines.push(item.description);
  lines.push("");
  lines.push("## Evidence");
  for (const ev of item.evidence) {
    lines.push(
      `- **${ev.eventName}** (${formatDate(ev.date)}) — weight ${ev.weight}/5 — [${ev.source}](${ev.url})`
    );
  }
  lines.push("");
  lines.push("## Related");
  lines.push(
    item.relatedKnowledge
      .map((k) => `- [${k}](/project/${slug}/knowledge/${k})`)
      .join("\n") || "_none_"
  );
  return lines.join("\n");
}

export function buildConflictMarkdown(
  c: Conflict,
  slug: string
): string {
  const lines: string[] = [];
  lines.push(`# ${c.id} — ${c.title}`);
  lines.push("");
  lines.push(
    `**Severity:** ${c.severity} · **Status:** ${c.status} · **Category:** ${c.category} · **Phase:** ${c.affectedPhase}`
  );
  lines.push("");
  lines.push(c.description);
  lines.push("");
  lines.push("## Version A");
  lines.push(
    `> ${c.versionA.value}\n>\n> Source: [${c.versionA.source}](${c.versionA.url}) — ${formatDate(c.versionA.date)} — ${c.versionA.evidence}`
  );
  lines.push("");
  lines.push("## Version B");
  lines.push(
    `> ${c.versionB.value}\n>\n> Source: [${c.versionB.source}](${c.versionB.url}) — ${formatDate(c.versionB.date)} — ${c.versionB.evidence}`
  );
  if (c.resolution) {
    lines.push("");
    lines.push(`## Resolution\n${c.resolution}`);
  }
  lines.push("");
  lines.push("## Affected Knowledge");
  lines.push(
    c.affectedKnowledge
      .map((k) => `- [${k}](/project/${slug}/knowledge/${k})`)
      .join("\n") || "_none_"
  );
  return lines.join("\n");
}

export function buildReportMarkdown(
  project: Project,
  knowledge: KnowledgeItem[],
  events: TimelineEvent[]
): string {
  const lines: string[] = [];
  lines.push(`# ${project.name} — CIF Intelligence Report`);
  lines.push("");
  lines.push(`> Generated by Intelligence Workspace · ${new Date().toISOString().slice(0, 10)}`);
  lines.push("");
  lines.push("## Summary");
  lines.push(project.description);
  lines.push("");
  lines.push("## Metrics");
  lines.push("");
  lines.push("| Metric | Value |");
  lines.push("| --- | --- |");
  lines.push(`| CIF Score | ${project.cifScore} |`);
  lines.push(`| Confidence | ${project.confidence}% |`);
  lines.push(`| Knowledge | ${project.knowledgeCount} |`);
  lines.push(`| Conflicts | ${project.conflictCount} |`);
  lines.push(`| Coverage | ${project.coverage}% |`);
  lines.push(`| Entities | ${project.entityCount} |`);
  lines.push("");
  lines.push("## CIF Dimensions");
  lines.push("");
  lines.push("| Dimension | Score | Weight | Contribution |");
  lines.push("| --- | --- | --- | --- |");
  for (const d of project.qa.dimensions) {
    lines.push(`| ${d.label} | ${d.score} | ${d.weight}% | ${Math.round(d.score * d.weight) / 100} |`);
  }
  lines.push("");
  lines.push("## Key Knowledge");
  lines.push("");
  for (const k of knowledge.slice(0, 6)) {
    lines.push(`- **${k.id}** ${k.name} — ${k.confidence}% confidence, ${k.status} ([detail](/project/${project.slug}/knowledge/${k.id}))`);
  }
  lines.push("");
  lines.push("## Recent Timeline");
  lines.push("");
  for (const ev of [...events].sort((a, b) => b.date.localeCompare(a.date)).slice(0, 8)) {
    lines.push(`- **${formatDate(ev.date)}** ${ev.name} (${ev.type})`);
  }
  lines.push("");
  lines.push("---");
  lines.push("_Generated by Intelligence Workspace · CIF v1.0_");
  return lines.join("\n");
}
